name: AzureDevOps Contribution API

on:
  push:
    branches: [ master, main ]
    paths:
      - 'src/Contribution.Common/**'
      - 'src/Contribution.AzureDevOps/**'
      - '.github/workflows/Contribution.AzureDevOps.yaml'
  # # Not sure if needed as of now cuz build are pushed straight to Azure Web App Service
  # pull_request:
  #   branches: [ master, main ]
  #   paths:
  #     - 'src/Contribution.Common/**'
  #     - 'src/Contribution.AzureDevOps/**'

permissions:
      id-token: write
      contents: read

env:
  AZURE_WEBAPP_NAME: az-c-api
  AZURE_WEBAPP_PACKAGE_PATH: '.'
  DOTNET_VERSION: '9.0.x'
  COMMON_PROJECT_PATH: 'src/Contribution.Common/Contribution.Common.csproj'
  AZUREDEVOPS_PROJECT_PATH: 'src/Contribution.AzureDevOps/Contribution.AzureDevOps.csproj'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # Check out the repo
      - uses: actions/checkout@main
      - uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      
      # Setup .NET Core SDK
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }} 
      
      # Build Common project first
      - name: Build Contribution.Common
        run: |
          dotnet restore ${{ env.COMMON_PROJECT_PATH }}
          dotnet build ${{ env.COMMON_PROJECT_PATH }} --configuration Release --no-restore
      
      # Build and test Contribution.AzureDevOps
      - name: Build Contribution.AzureDevOps
        run: |
          dotnet restore ${{ env.AZUREDEVOPS_PROJECT_PATH }}
          dotnet build ${{ env.AZUREDEVOPS_PROJECT_PATH }} --configuration Release --no-restore
      
      # Run tests (if any test projects exist)
      - name: Run tests
        run: |
          if [ -d "tests" ]; then
            dotnet test --configuration Release --no-build --verbosity normal
          else
            echo "No test projects found, skipping tests"
          fi
      
      # Publish the application
      - name: Publish Contribution.AzureDevOps
        run: |
          dotnet publish ${{ env.AZUREDEVOPS_PROJECT_PATH }} -c Release -o '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/azcapi' --no-restore
      
      # Upload build artifacts for debugging
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: contribution-api-build
          path: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/azcapi'
          retention-days: 30
          
      # Deploy to Azure Web apps
      - name: 'Run Azure webapp deploy action using publish profile credentials'
        uses: azure/webapps-deploy@v3
        with: 
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/azcapi'
      
      - name: logout
        run: |
          az logout