name: Hub Contribution API

on:
  push:
    branches: [ master, main ]
    paths:
      - 'src/Contribution.Common/**'
      - 'src/Contribution.Hub/**'
      - '.github/workflows/Contribution.Hub.yaml'
  # # Not sure if needed as of now cuz build are pushed straight to Azure Web App Service
  # pull_request:
  #   branches: [ master, main ]
  #   paths:
  #     - 'src/Contribution.Common/**'
  #     - 'src/Contribution.Hub/**'

env:
  AZURE_WEBAPP_NAME: c-hub-api
  AZURE_WEBAPP_PACKAGE_PATH: '.'
  DOTNET_VERSION: '9.0.x'
  ASPNETCORE_ENVIRONMENT: Production
  PROJECT_PATH: 'src/Contribution.Hub/Contribution.Hub.csproj'

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      id-token: write
      contents: read

    steps:
      # Check out the repo
      - uses: actions/checkout@main
      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_HUB }}

      # Setup .NET Core SDK
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }} 
      
      # Build and test Contribution.Hub
      - name: Build Contribution.Hub
        run: |
          dotnet restore ${{ env.PROJECT_PATH }}
          dotnet build ${{ env.PROJECT_PATH }} --configuration Release --no-restore
      
      # Run tests (if any test projects exist)
      - name: Run tests
        run: |
          if [ -d "tests" ]; then
            dotnet test --configuration Release --no-build --verbosity normal
          else
            echo "No test projects found, skipping tests"
          fi
      
      # Publish the application
      - name: Publish Contribution.Hub
        run: |
          dotnet publish ${{ env.PROJECT_PATH }} -c Release -o '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/${{ env.AZURE_WEBAPP_NAME }}' --no-restore

      # Setup Google Application Credentials
      - name: Setup Google Application Credentials
        run: |
          echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}" | base64 --decode > '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/${{ env.AZURE_WEBAPP_NAME }}/contribution-manager.json'
          echo "Google credentials configured successfully"
      
      # # No Upload build artifacts for debugging until google credentials json is sorted via env
      # - name: Upload build artifacts
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: contribution-api-build
      #     path: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/${{ env.AZURE_WEBAPP_NAME }}'
      #     retention-days: 30
          
      # Deploy to Azure Web apps
      - name: 'Run Azure webapp deploy action using publish profile credentials'
        uses: azure/webapps-deploy@v3
        with: 
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/${{ env.AZURE_WEBAPP_NAME }}'
      
      - name: logout
        run: |
          az logout